#! /usr/bin/perl

use strict;
use Cwd;
use File::Spec;

BEGIN {
  $^W = 1;  # Use warnings
  my $curdir = File::Spec->canonpath( Cwd::cwd() );
  unless ($curdir eq '/home/dave/src/AudioFile-Info-MP3-Tag') {
    die ('This script must be run from /home/dave/src/AudioFile-Info-MP3-Tag, not '."$curdir\n".
	 "Please re-run the Build.PL script here.\n");
  }
  @INC = 
    (
     '/home/dave/src/AudioFile-Info-MP3-Tag/lib',
     '/usr/lib/perl5/5.8.1/i386-linux-thread-multi',
     '/usr/lib/perl5/5.8.1',
     '/usr/lib/perl5/site_perl/5.8.1/i386-linux-thread-multi',
     '/usr/lib/perl5/site_perl/5.8.1',
     '/usr/lib/perl5/site_perl',
     '/usr/lib/perl5/vendor_perl/5.8.1/i386-linux-thread-multi',
     '/usr/lib/perl5/vendor_perl/5.8.1',
     '/usr/lib/perl5/vendor_perl/5.8.0/i386-linux-thread-multi',
     '/usr/lib/perl5/vendor_perl/5.8.0',
     '/usr/lib/perl5/vendor_perl',
     '/home/dave/src/AudioFile-Info-MP3-Tag'
    );
}

use AudioFile::Info::Build;

if (-e 'Build.PL' and not AudioFile::Info::Build->up_to_date("Build.PL", $0)) {
   warn "Warning: Build.PL has been altered.  You may need to run 'perl Build.PL' again.
";
}

# This should have just enough arguments to be able to bootstrap the rest.
my $build = AudioFile::Info::Build->resume (
  properties => {
    config_dir => '/home/dave/src/AudioFile-Info-MP3-Tag/_build',
  },
);

$build->dispatch;
